"""Configurações visuais do ADM SmartCadastro."""


# Fonte principal
FONTE_PRINCIPAL = "Segoe UI"


# Tamanhos das fontes
TAMANHO_TITULO = 27
TAMANHO_SUBTITULO = 14
TAMANHO_TEXTO = 13
TAMANHO_TEXTO_DESTAQUE = 15
TAMANHO_BOTAO = 14
TAMANHO_TABELA = 10


# Cores principais
COR_FUNDO = "#FFFFFF"

COR_AZUL = "#2563EB"
COR_AZUL_HOVER = "#1D4ED8"
COR_AZUL_CLARO = "#EAF1FF"
COR_AZUL_CLARO_HOVER = "#DCE8FF"

COR_TEXTO = "#1F2937"
COR_TEXTO_SECUNDARIO = "#6B7280"
COR_TEXTO_BOTAO = "#FFFFFF"

COR_BORDA = "#D1D5DB"
COR_BORDA_ESCURA = "#9CA3AF"

COR_FUNDO_SECUNDARIO = "#F3F4F6"